In [1]:
import tensorflow as tf
import numpy as np
from user_embedding import UserModel
from item_embedding import ItemModel
from rating_model import RatingModel
from recommender import Recommender

In [4]:
import os

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

import tensorflow_recommenders as tfrs

from recommender import Recommender
from user_embedding import UserModel
from item_embedding import ItemModel

# from utils import dataset_to_dataframe
from datetime import datetime

train_ds = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_train") #data\ratings_train
test_ds = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_test")
ratings_all = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_all")

movie_titles = ratings_all.batch(1_000_000).map(lambda x: x["movie_title"])
user_ids = ratings_all.batch(1_000_000).map(lambda x: x["user_id"])

unique_movie_titles = np.unique(np.concatenate(list(movie_titles)))
unique_user_ids = np.unique(np.concatenate(list(user_ids)))

timestamps = np.concatenate(list(ratings_all.map(lambda x: x["timestamp"]).batch(100)))

max_timestamp = timestamps.max()
min_timestamp = timestamps.min()


timestamp_buckets = np.linspace(
    min_timestamp, max_timestamp, num=1000,
)

user_model = UserModel(
    use_timestamp = True,
    unique_user_ids = unique_user_ids,
    timestamps = timestamps,
    timestamp_buckets = timestamp_buckets
)

item_model = ItemModel(
    unique_movie_titles = unique_movie_titles
)

# model = Recommender(
#     user_model = user_model,
#     item_model = item_model
#     )

model = Recommender(
    use_timestamp = True,
    unique_user_ids = unique_user_ids,
    unique_movie_titles = unique_movie_titles,
    timestamps = timestamps,
    timestamp_buckets = timestamp_buckets
)

c:\Users\bpadmin\anaconda3\envs\tensorflow_cuda\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [35]:
decode_string(b'101')

'101'

In [36]:
str(b'101')

"b'101'"

In [38]:
def decode_string(x):
    return x.decode("utf-8")  # Replace "utf-8" with the appropriate encoding

dataset = train_ds.map(lambda x: {
  "user_id": x["user_id"].decode('utf-8')
})

AttributeError: in user code:

    File "C:\Users\naradaw\AppData\Local\Temp\ipykernel_31088\3918727658.py", line 5, in None  *
        lambda x: {

    AttributeError: 'Tensor' object has no attribute 'decode'


In [7]:
next(iter(train_ds))

{'user_id': <tf.Tensor: shape=(8192,), dtype=string, numpy=array([b'378', b'234', b'334', ..., b'10', b'646', b'136'], dtype=object)>,
 'user_rating': <tf.Tensor: shape=(8192,), dtype=float32, numpy=array([5., 5., 4., ..., 4., 2., 4.], dtype=float32)>,
 'timestamp': <tf.Tensor: shape=(8192,), dtype=int64, numpy=
 array([880045935, 892333798, 891546206, ..., 877892276, 888529180,
        882693723], dtype=int64)>,
 'movie_title': <tf.Tensor: shape=(8192,), dtype=string, numpy=
 array([b'Room with a View, A (1986)', b'Cinema Paradiso (1988)',
        b'Duck Soup (1933)', ..., b'Raising Arizona (1987)',
        b'Flubber (1997)', b'Sense and Sensibility (1995)'], dtype=object)>}

In [5]:
# log_dir = "../../logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
# tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))


train_ds = train_ds.shuffle(100_000).batch(8192) #.cache()

model.fit(
    train_ds, epochs=1, verbose = 1,
    # callbacks=[tensorboard_callback]
    )

10/10 [==============================] - 7s 42ms/step - root_mean_squared_error: 2.1808 - loss: 4.3718 - regularization_loss: 0.0000e+00 - total_loss: 4.3718


In [11]:
#save model
base = '..\..\models'
model_name = 'tf_rating_{}'.format(datetime.now().strftime("%Y_%m_%d_%H_%M"))
save_path = os.path.join(base,model_name)

model.save_weights(save_path)
# model.save(save_path) #, save_format="keras"
# tf.saved_model.save(model, "export")

# model.evaluate(cached_test, return_dict=True)

In [12]:
loaded_model = Recommender(
    use_timestamp = True,
    unique_user_ids = unique_user_ids,
    unique_movie_titles = unique_movie_titles,
    timestamps = timestamps,
    timestamp_buckets = timestamp_buckets
)

In [16]:
loaded_model.load_weights(r"..\..\models\tf_rating_2024_04_02_15_01")

In [19]:
loaded_model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))

In [22]:
loaded_model.evaluate(test_ds.shuffle(100_000).batch(1024), return_dict=True)

TypeError: 'NoneType' object is not callable

In [3]:
loaded.evaluate(test_ds, return_dict=True)

AttributeError: '_UserObject' object has no attribute 'evaluate'

In [2]:
train_ds = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_train") #data\ratings_train
test_ds = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_test")
ratings_all = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_all")

movie_titles = ratings_all.batch(1_000_000).map(lambda x: x["movie_title"])
user_ids = ratings_all.batch(1_000_000).map(lambda x: x["user_id"])

unique_movie_titles = np.unique(np.concatenate(list(movie_titles)))
unique_user_ids = np.unique(np.concatenate(list(user_ids)))

timestamps = np.concatenate(list(ratings_all.map(lambda x: x["timestamp"]).batch(100)))

max_timestamp = timestamps.max()
min_timestamp = timestamps.min()

timestamp_buckets = np.linspace(
    min_timestamp, max_timestamp, num=1000,
)

In [14]:
list(unique_user_ids)

[b'1',
 b'10',
 b'100',
 b'101',
 b'102',
 b'103',
 b'104',
 b'105',
 b'106',
 b'107',
 b'108',
 b'109',
 b'11',
 b'110',
 b'111',
 b'112',
 b'113',
 b'114',
 b'115',
 b'116',
 b'117',
 b'118',
 b'119',
 b'12',
 b'120',
 b'121',
 b'122',
 b'123',
 b'124',
 b'125',
 b'126',
 b'127',
 b'128',
 b'129',
 b'13',
 b'130',
 b'131',
 b'132',
 b'133',
 b'134',
 b'135',
 b'136',
 b'137',
 b'138',
 b'139',
 b'14',
 b'140',
 b'141',
 b'142',
 b'143',
 b'144',
 b'145',
 b'146',
 b'147',
 b'148',
 b'149',
 b'15',
 b'150',
 b'151',
 b'152',
 b'153',
 b'154',
 b'155',
 b'156',
 b'157',
 b'158',
 b'159',
 b'16',
 b'160',
 b'161',
 b'162',
 b'163',
 b'164',
 b'165',
 b'166',
 b'167',
 b'168',
 b'169',
 b'17',
 b'170',
 b'171',
 b'172',
 b'173',
 b'174',
 b'175',
 b'176',
 b'177',
 b'178',
 b'179',
 b'18',
 b'180',
 b'181',
 b'182',
 b'183',
 b'184',
 b'185',
 b'186',
 b'187',
 b'188',
 b'189',
 b'19',
 b'190',
 b'191',
 b'192',
 b'193',
 b'194',
 b'195',
 b'196',
 b'197',
 b'198',
 b'199',
 b'2',
 b'20'

In [3]:
user_model = UserModel(
    use_timestamp = True,
    unique_user_ids = unique_user_ids,
    timestamps = timestamps,
    timestamp_buckets = timestamp_buckets
)

In [4]:
item_model = ItemModel(
    unique_movie_titles = unique_movie_titles
)

In [5]:
rating_model = RatingModel(
    user_model = user_model,
    item_model = item_model
)

In [6]:
from recommender import Recommender

model = Recommender(
    user_model = user_model,
    item_model = item_model
    )

model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))

In [7]:
train_ds_cached = train_ds.shuffle(100_000).batch(8192).cache()

In [8]:
next(train_ds_cached.take(1).as_numpy_iterator())

{'user_id': array([b'450', b'615', b'77', ..., b'538', b'795', b'684'], dtype=object),
 'movie_title': array([b'One Fine Day (1996)', b'Dave (1993)',
        b'Empire Strikes Back, The (1980)', ...,
        b'American President, The (1995)', b'Stargate (1994)',
        b'Casablanca (1942)'], dtype=object),
 'timestamp': array([882396153, 879449211, 884752562, ..., 877107765, 883254564,
        878576905], dtype=int64),
 'user_rating': array([3., 4., 3., ..., 3., 4., 5.], dtype=float32)}

In [12]:
model.fit(train_ds_cached, epochs=10, verbose = 1)

Epoch 1/10


10/10 [==============================] - 0s 30ms/step - root_mean_squared_error: 1.1467 - loss: 1.3075 - regularization_loss: 0.0000e+00 - total_loss: 1.3075
Epoch 2/10
10/10 [==============================] - 0s 15ms/step - root_mean_squared_error: 1.1186 - loss: 1.2476 - regularization_loss: 0.0000e+00 - total_loss: 1.2476
Epoch 3/10
10/10 [==============================] - 0s 13ms/step - root_mean_squared_error: 1.1075 - loss: 1.2231 - regularization_loss: 0.0000e+00 - total_loss: 1.2231
Epoch 4/10
10/10 [==============================] - 0s 12ms/step - root_mean_squared_error: 1.0952 - loss: 1.1958 - regularization_loss: 0.0000e+00 - total_loss: 1.1958
Epoch 5/10
10/10 [==============================] - 0s 14ms/step - root_mean_squared_error: 1.0800 - loss: 1.1626 - regularization_loss: 0.0000e+00 - total_loss: 1.1626
Epoch 6/10
10/10 [==============================] - 0s 13ms/step - root_mean_squared_error: 1.0628 - loss: 1.1257 - regularization_loss: 0.0000e+00 - total_loss: 1.12

# Sandbox

In [10]:
import sys
sys.exit()

SystemExit: 

c:\Users\bpadmin\anaconda3\envs\tensorflow_cuda\lib\site-packages\IPython\core\interactiveshell.py:3513: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
train_rate_ds = train_ds_cached.map(
    lambda x: {
        'user_id' : x['user_id'],
        'timestamp' : x['timestamp'],
        'movie_title' : x['movie_title']
    })

In [ ]:
type(train_rate_ds.take(1))

tensorflow.python.data.ops.dataset_ops.TakeDataset

In [ ]:
# from rating_model import RatingModel

rating_model_v2 = RatingModel_v2(
    user_model = user_model,
    item_model = item_model
)

In [ ]:
train_ds_cached = train_ds.shuffle(100_000).batch(8192).cache()

In [ ]:
# first_b = train_rate_ds.take(1)
for batch in train_rate_ds:
    # print(batch)
    print(rating_model_v2(batch))
    # print(user_model(batch))

tf.Tensor(
[[-0.0278586 ]
 [-0.01198122]
 [ 0.00244341]
 ...
 [-0.02687048]
 [-0.01681492]
 [ 0.00500782]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[ 0.03001076]
 [-0.03635289]
 [-0.00816108]
 ...
 [-0.0179458 ]
 [-0.01056856]
 [-0.02847496]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[ 0.01747694]
 [-0.02926904]
 [-0.04106154]
 ...
 [-0.02373955]
 [-0.00013693]
 [-0.05582498]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[-0.0208011 ]
 [-0.00035297]
 [ 0.02468143]
 ...
 [-0.02326185]
 [ 0.01481644]
 [ 0.00186529]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[-0.0192941 ]
 [ 0.02675624]
 [-0.02800284]
 ...
 [-0.03645618]
 [-0.02075573]
 [ 0.003501  ]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[ 0.0059039 ]
 [-0.01196808]
 [-0.03702434]
 ...
 [ 0.00460922]
 [-0.00274516]
 [ 0.00819112]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[ 0.00377113]
 [-0.05971538]
 [ 0.02182457]
 ...
 [-0.02506855]
 [-0.02354168]
 [-0.03434455]], shape=(8192, 1), dtype=float32)
tf.Tensor(
[[-0.0103

In [ ]:
train_ds_cached = train_ds.shuffle(100_000).batch(8192).cache()

In [ ]:
next(train_ds_cached.take(1).as_numpy_iterator())

{'timestamp': array([884140853, 882397068, 888465216, ..., 881200491, 891350845,
        878192601], dtype=int64),
 'user_rating': array([3., 1., 4., ..., 3., 5., 4.], dtype=float32),
 'user_id': array([b'201', b'13', b'631', ..., b'281', b'7', b'299'], dtype=object),
 'movie_title': array([b'2 Days in the Valley (1996)', b'Amityville 3-D (1983)',
        b'Evita (1996)', ..., b'Edge, The (1997)',
        b'Butch Cassidy and the Sundance Kid (1969)',
        b'Brothers McMullen, The (1995)'], dtype=object)}

In [ ]:
type(train_ds_cached)

tensorflow.python.data.ops.dataset_ops.CacheDataset

In [ ]:
model.fit(train_ds_cached, epochs=10, verbose = 1)

In [ ]:
import tensorflow as tf
import pandas as pd

def dataset_to_dataframe(dataset):
  
  data = []
  for element in dataset.as_numpy_iterator():
    data.append(element)

  return pd.DataFrame(data)

df = dataset_to_dataframe(train_loaded)
# print(df)


In [ ]:
df.head()

timestamp user_id  user_rating                    movie_title
0  885409515  b'681'          4.0         b'Postman, The (1997)'
1  883388887  b'442'          2.0             b'Clueless (1995)'
2  891249586  b'932'          5.0  b'Maltese Falcon, The (1941)'
3  878044851  b'506'          5.0      b'His Girl Friday (1940)'
4  880130613   b'18'          4.0            b'Quiz Show (1994)'

In [ ]:
max(df.timestamp.unique().tolist())

893286638

In [ ]:
import numpy as np

ratings_all = tf.data.Dataset.load("D:/dev work/recommender systems/CARS/data/ratings_all")

timestamps = np.concatenate(list(ratings_all.map(lambda x: x["timestamp"]).batch(100)))


In [ ]:
timestamps.shape

(100000,)